/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    projects: Project;
    inquiries: Inquiry;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Page copy for Home, Work, About, and Contact. Edit text here — the front end reads these documents.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * home, work, about, or contact. Used as the route key.
   */
  slug: string;
  eyebrow?: string | null;
  headline?: string | null;
  /**
   * Muted or gold second half of the headline.
   */
  headlineAccent?: string | null;
  lede?: string | null;
  /**
   * Structured bits of copy (hero lines, process forms, résumé rows). The key field is how the page finds each block — keep keys stable.
   */
  blocks?:
    | {
        key: string;
        label?: string | null;
        title?: string | null;
        kicker?: string | null;
        meta?: string | null;
        href?: string | null;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Work slots. BioBuild is the only filled case. AT&T and T-Mobile stay pending clearance until real screenshots exist. Do not invent metrics or fake UI.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  index: string;
  title: string;
  client: string;
  status: 'filled' | 'tbd' | 'reserved';
  kind: 'case' | 'corporate' | 'reserved';
  /**
   * URL segment under /work. Shared by sibling slots (both AT&T cards use att).
   */
  caseSlug?: string | null;
  summary: string;
  tags?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  href: string;
  /**
   * CDN or site URL. Leave empty for placeholders — do not paste stock photos.
   */
  imageUrl?: string | null;
  imageAlt?: string | null;
  liveUrl?: string | null;
  liveLabel?: string | null;
  showOnRail?: boolean | null;
  railOrder?: number | null;
  role?: string | null;
  year?: string | null;
  dates?: string | null;
  location?: string | null;
  stack?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  accent?: ('moss' | 'crimson' | 'gold') | null;
  log?:
    | {
        stamp: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  sections?:
    | {
        anchor: string;
        eyebrow?: string | null;
        title: string;
        /**
         * Separate paragraphs with a blank line.
         */
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  highlights?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  facts?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  gallery?:
    | {
        url: string;
        alt: string;
        caption?: string | null;
        placement: 'hero' | 'problem' | 'approach';
        id?: string | null;
      }[]
    | null;
  /**
   * Empty screenshot slots for NDA placeholders. No fake product UI.
   */
  plates?:
    | {
        label: string;
        aspect: 'wide' | 'landscape' | 'portrait';
        id?: string | null;
      }[]
    | null;
  nextHref?: string | null;
  nextIndex?: string | null;
  nextTitle?: string | null;
  ndaNote?: string | null;
  closing?: {
    eyebrow?: string | null;
    title?: string | null;
    accent?: string | null;
    body?: string | null;
    primaryLabel?: string | null;
    primaryHref?: string | null;
    secondaryLabel?: string | null;
    secondaryHref?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Messages saved from the public contact form. Nothing is emailed automatically — reply from the address in Site settings. Extra $0, no mail provider.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  name: string;
  email: string;
  projectType?: string | null;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  eyebrow?: T;
  headline?: T;
  headlineAccent?: T;
  lede?: T;
  blocks?:
    | T
    | {
        key?: T;
        label?: T;
        title?: T;
        kicker?: T;
        meta?: T;
        href?: T;
        body?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  index?: T;
  title?: T;
  client?: T;
  status?: T;
  kind?: T;
  caseSlug?: T;
  summary?: T;
  tags?:
    | T
    | {
        label?: T;
        id?: T;
      };
  href?: T;
  imageUrl?: T;
  imageAlt?: T;
  liveUrl?: T;
  liveLabel?: T;
  showOnRail?: T;
  railOrder?: T;
  role?: T;
  year?: T;
  dates?: T;
  location?: T;
  stack?:
    | T
    | {
        label?: T;
        id?: T;
      };
  accent?: T;
  log?:
    | T
    | {
        stamp?: T;
        label?: T;
        id?: T;
      };
  sections?:
    | T
    | {
        anchor?: T;
        eyebrow?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  highlights?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  facts?:
    | T
    | {
        text?: T;
        id?: T;
      };
  gallery?:
    | T
    | {
        url?: T;
        alt?: T;
        caption?: T;
        placement?: T;
        id?: T;
      };
  plates?:
    | T
    | {
        label?: T;
        aspect?: T;
        id?: T;
      };
  nextHref?: T;
  nextIndex?: T;
  nextTitle?: T;
  ndaNote?: T;
  closing?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        accent?: T;
        body?: T;
        primaryLabel?: T;
        primaryHref?: T;
        secondaryLabel?: T;
        secondaryHref?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  projectType?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Name, email, LinkedIn, navigation, and footer. Do not add a personal phone number.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  name: string;
  roleLine?: string | null;
  email: string;
  linkedinUrl?: string | null;
  linkedinLabel?: string | null;
  location?: string | null;
  /**
   * Shown in the header. Clear this when the site should no longer say private preview.
   */
  previewBadge?: string | null;
  primaryCtaLabel?: string | null;
  primaryCtaHref?: string | null;
  footerBlurb?: string | null;
  copyright?: string | null;
  footerNote?: string | null;
  navLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footerLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  roleLine?: T;
  email?: T;
  linkedinUrl?: T;
  linkedinLabel?: T;
  location?: T;
  previewBadge?: T;
  primaryCtaLabel?: T;
  primaryCtaHref?: T;
  footerBlurb?: T;
  copyright?: T;
  footerNote?: T;
  navLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}